  fun ref take_error(error': NullablePointer[GErrorT]): None =>
    GSimpleAsyncResultP.take_error(this, error')
