  fun ref had_error(): I32 =>
    GTaskP.had_error(this)
